import { PALETTE_COLORS } from '../domain/catalog';
import type { GameState, Point } from '../domain/types'; import { ANOMALIES, PLOTS, SEED_NAMES, SHRINES, WORLD } from '../domain/world';
export function cameraFor(player:Point,width:number,height:number){return{x:Math.max(0,Math.min(WORLD.width-width,player.x-width/2)),y:Math.max(0,Math.min(WORLD.height-height,player.y-height/2))}}
export function worldToScreen(p:Point,camera:Point){return{x:p.x-camera.x,y:p.y-camera.y}}
export function createCanvasRenderer(canvas:HTMLCanvasElement){const context=canvas.getContext('2d');if(!context)throw new Error('Canvas 2D is unavailable.');const ctx=context;let width=innerWidth,height=innerHeight,scale=devicePixelRatio||1,camera={x:0,y:0};
 const resize=()=>{width=innerWidth;height=innerHeight;scale=devicePixelRatio||1;canvas.width=width*scale;canvas.height=height*scale;canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;ctx.setTransform(scale,0,0,scale,0,0)};
 function blob(x:number,y:number,r:number,color:string,points=10){ctx.beginPath();for(let i=0;i<=points;i++){const a=i/points*Math.PI*2,rr=r*(.88+Math.sin(i*2.7)*.08);const px=x+Math.cos(a)*rr,py=y+Math.sin(a)*rr;if(i===0)ctx.moveTo(px,py);else ctx.lineTo(px,py)}ctx.fillStyle=color;ctx.fill()}
 function drawAvatar(state:GameState,now:number){const p=worldToScreen(state.player,camera),[base,accent]=PALETTE_COLORS[state.character.appearance.palette];ctx.save();ctx.translate(p.x,p.y+Math.sin(now/330)*2);ctx.globalAlpha=state.effects.fadingUntil>now?.48:1;ctx.shadowColor='#0a161180';ctx.shadowBlur=12;ctx.shadowOffsetY=9;ctx.fillStyle=base;ctx.strokeStyle='#18231f';ctx.lineWidth=3;
  const body=state.character.appearance.body;ctx.beginPath();if(body==='fox'){ctx.moveTo(-22,-18);ctx.lineTo(-15,-42);ctx.lineTo(-2,-27);ctx.lineTo(16,-42);ctx.lineTo(23,-16);ctx.quadraticCurveTo(26,22,0,30);ctx.quadraticCurveTo(-27,22,-22,-18)}else if(body==='moth'){ctx.ellipse(0,0,12,29,0,0,Math.PI*2);ctx.moveTo(-8,-7);ctx.bezierCurveTo(-50,-43,-52,22,-12,18);ctx.moveTo(8,-7);ctx.bezierCurveTo(50,-43,52,22,12,18)}else if(body==='bird'){ctx.ellipse(0,0,25,30,0,0,Math.PI*2);ctx.moveTo(18,-8);ctx.lineTo(38,0);ctx.lineTo(18,7)}else{ctx.moveTo(0,-38);ctx.bezierCurveTo(34,-24,31,20,0,34);ctx.bezierCurveTo(-31,20,-34,-24,0,-38)}ctx.closePath();ctx.fill();ctx.stroke();ctx.shadowColor='transparent';ctx.fillStyle=accent;ctx.beginPath();ctx.arc(-8,-8,4,0,Math.PI*2);ctx.arc(8,-8,4,0,Math.PI*2);ctx.fill();ctx.strokeStyle=accent;ctx.lineWidth=2;const mark=state.character.appearance.mark;if(mark==='rings'){ctx.beginPath();ctx.arc(0,10,13,0,Math.PI*2);ctx.stroke()}else if(mark==='cracks'||state.effects.fragileUntil>now){ctx.beginPath();ctx.moveTo(-4,3);ctx.lineTo(4,10);ctx.lineTo(-2,19);ctx.stroke()}else if(mark==='map-lines'){ctx.beginPath();ctx.moveTo(-16,13);ctx.quadraticCurveTo(0,0,16,14);ctx.stroke()}else{for(const x of[-12,0,12]){ctx.beginPath();ctx.arc(x,12+Math.abs(x)/2,2,0,Math.PI*2);ctx.fill()}}ctx.restore()}
 function render(state:GameState,now:number){camera=cameraFor(state.player,width,height);ctx.clearRect(0,0,width,height);ctx.fillStyle='#294039';ctx.fillRect(0,0,width,height);ctx.save();ctx.translate(-camera.x,-camera.y);
  ctx.fillStyle='#344e44';ctx.fillRect(0,0,WORLD.width,WORLD.height);for(let i=0;i<110;i++)blob((i*271)%WORLD.width,(i*157)%WORLD.height,5+(i%8),'#8fa37a22',7);
  ctx.strokeStyle='#bea66a33';ctx.lineWidth=120;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(700,420);ctx.bezierCurveTo(1250,420,1330,980,1900,900);ctx.bezierCurveTo(2420,820,2450,1230,2860,1100);ctx.stroke();
  ctx.fillStyle='#263a34';ctx.fillRect(WORLD.sanctuary.x,WORLD.sanctuary.y,WORLD.sanctuary.w,WORLD.sanctuary.h);ctx.strokeStyle='#e7c86d99';ctx.lineWidth=3;ctx.setLineDash([13,10]);ctx.strokeRect(WORLD.sanctuary.x+12,WORLD.sanctuary.y+12,WORLD.sanctuary.w-24,WORLD.sanctuary.h-24);ctx.setLineDash([]);ctx.fillStyle='#f0db9a';ctx.font='700 24px Georgia';ctx.fillText('THE SANCTUARY',130,150);
  for(const plot of PLOTS){ctx.beginPath();ctx.ellipse(plot.position.x,plot.position.y,58,38,0,0,Math.PI*2);ctx.fillStyle='#172822';ctx.fill();ctx.strokeStyle='#b99c64';ctx.stroke();const seed=state.plantings[plot.id];if(seed){blob(plot.position.x,plot.position.y-24,24,'#e4bd61',8);ctx.fillStyle='#f3ead9';ctx.font='12px DM Mono';ctx.textAlign='center';ctx.fillText(SEED_NAMES[seed]??seed,plot.position.x,plot.position.y+62)}}
  for(const shrine of SHRINES){ctx.save();ctx.translate(shrine.position.x,shrine.position.y);ctx.rotate(Math.PI/4);ctx.fillStyle=state.borrowedGift===shrine.gift?'#f4cf70':'#9a8bb3';ctx.fillRect(-25,-25,50,50);ctx.strokeStyle='#f8ebc7';ctx.lineWidth=3;ctx.strokeRect(-25,-25,50,50);ctx.restore();ctx.fillStyle='#eee5d1';ctx.font='12px DM Mono';ctx.textAlign='center';ctx.fillText(shrine.gift.toUpperCase(),shrine.position.x,shrine.position.y+52)}
  for(const a of ANOMALIES){const stage=state.anomalies[a.id]??0;blob(a.position.x,a.position.y,36+stage*7,a.color,8);ctx.strokeStyle='#fbefce';ctx.lineWidth=stage===a.states.length-1?3:1;ctx.beginPath();ctx.arc(a.position.x,a.position.y,47+stage*8,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#fff5dc';ctx.font='600 14px Nunito Sans';ctx.textAlign='center';ctx.fillText(a.states[stage]??a.name,a.position.x,a.position.y+70)}
  ctx.restore();drawAvatar(state,now);}
 resize();return{resize,render,worldToScreen:(p:Point)=>worldToScreen(p,camera)} }
