import { AI_CONTEXT_PACKET, validateCharacterCard } from '../domain/character'; import { SEED_NAMES } from '../domain/world'; import type { Character, GameState } from '../domain/types';
export interface PanelActions{onGenerate():void;onImport(character:Character):void;onReset():void}
export function createPanels(root:HTMLElement,actions:PanelActions){
 const clear=()=>{root.replaceChildren()}; const shell=(title:string)=>{clear();const section=document.createElement('section');section.className='modal';section.innerHTML=`<div class="modal-body"><div class="modal-head"><div><span class="eyebrow">The Unwritten / prototype</span><h2></h2></div><button class="close" aria-label="Close">×</button></div><div data-slot="content"></div></div>`;(section.querySelector('h2') as HTMLElement).textContent=title;section.querySelector('.close')?.addEventListener('click',clear);root.append(section);return section.querySelector<HTMLElement>('[data-slot=content]')!};
 function showStart(){clear();const s=document.createElement('section');s.className='modal start';s.dataset.testid='start-panel';s.innerHTML=`<div class="start-copy"><span class="eyebrow">A character foundry / local prototype</span><h1>The<br>Unwritten</h1><p class="lead">Bring a being imagined with any AI into a quiet world. Its story becomes a balanced gift, a burden, and a peculiar way of seeing.</p></div><div class="start-actions"><button class="button primary" data-action="generate">Surprise Me</button><button class="button" data-action="import">Import Character</button><button class="button ghost" data-action="ai">Create with your AI</button><p class="hint">No account. No AI key. The game—not the prompt—controls power.</p></div>`;s.querySelector('[data-action=generate]')?.addEventListener('click',actions.onGenerate);s.querySelector('[data-action=import]')?.addEventListener('click',showImport);s.querySelector('[data-action=ai]')?.addEventListener('click',showAI);root.append(s)}
 function showImport(){const c=shell('Import a character');c.innerHTML=`<p>Paste the JSON card your AI created. Numbers and unknown powers are ignored.</p><textarea aria-label="Character JSON" spellcheck="false"></textarea><div data-errors></div><div class="choice-row"><button class="button primary">Bring character into the world</button><button class="button ghost" data-back>Back</button></div>`;const box=c.querySelector('textarea')!,errors=c.querySelector<HTMLElement>('[data-errors]')!;c.querySelector('.primary')?.addEventListener('click',()=>{const result=validateCharacterCard(box.value);if(result.ok){actions.onImport(result.character);clear()}else{errors.className='errors';errors.dataset.testid='import-errors';errors.replaceChildren(...result.errors.map(e=>{const p=document.createElement('div');p.textContent=e;return p}))}});c.querySelector('[data-back]')?.addEventListener('click',showStart)}
 function showAI(){const c=shell('Create with your AI');c.innerHTML=`<p>Copy this context into any AI. Ask it to invent your being, then paste its JSON into Import Character.</p><textarea readonly aria-label="AI creation context"></textarea><div class="choice-row"><button class="button primary">Copy creation context</button><button class="button" data-import>Import the result</button></div>`;c.querySelector('textarea')!.value=AI_CONTEXT_PACKET;c.querySelector('.primary')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(AI_CONTEXT_PACKET);c.querySelector('.primary')!.textContent='Copied'});c.querySelector('[data-import]')?.addEventListener('click',showImport)}
 function trait(label:string,name:string,description:string){const d=document.createElement('div');d.className='trait';const b=document.createElement('b');b.textContent=label;const strong=document.createElement('strong');strong.textContent=name;const p=document.createElement('p');p.textContent=description;d.append(b,strong,p);return d}
 function showCharacter(character:Character){const c=shell('Character passport'),pass=document.createElement('div');pass.className='passport';const preview=document.createElement('div');preview.className='avatar-preview';preview.textContent=`${character.appearance.material} ${character.appearance.body}`;const info=document.createElement('div'),h=document.createElement('h3'),p=document.createElement('p');h.textContent=character.name;p.textContent=character.description;const grid=document.createElement('div');grid.className='trait-grid';grid.append(trait('Gift',character.gift.name,character.gift.description),trait('Burden',character.burden.name,character.burden.description),trait('Quirk',character.quirk.name,character.quirk.description));info.append(h,p,grid);pass.append(preview,info);c.append(pass)}
 function showJournal(state:GameState){const c=shell('Field journal');const summary=document.createElement('p');summary.textContent=`${state.discoveries.length} reactions remembered · ${state.seeds.length} seeds waiting · ${Object.keys(state.plantings).length} planted`;c.append(summary);const list=document.createElement('div');list.className='journal-list';if(!state.discoveries.length){const p=document.createElement('p');p.textContent='The first page is waiting. Find an anomaly and use your Gift.';list.append(p)}for(const item of state.discoveries){const d=document.createElement('div');d.className='journal-item';d.textContent=item;list.append(d)}c.append(list);if(state.seeds.length){const h=document.createElement('h3');h.textContent='Seed tray';const seeds=document.createElement('div');seeds.className='seed-grid';for(const seed of state.seeds){const d=document.createElement('div');d.className='seed';d.textContent=SEED_NAMES[seed]??seed;seeds.append(d)}c.append(h,seeds)}}
 function showHelp(){const c=shell('How to wander');c.innerHTML=`<div class="controls"><b>WASD / ARROWS</b> — move<br><b>F</b> — use your Gift on an anomaly<br><b>E</b> — inspect, borrow Resonance, or plant<br><b>J</b> — field journal<br><b>C</b> — character passport<br><br>Colored diamonds are Resonance Shrines. Borrow their Gift to complete two-step reactions. Your sanctuary is the marked plot in the northwest.</div><div class="choice-row"><button class="button danger">Reset all local progress</button></div>`;c.querySelector('.danger')?.addEventListener('click',()=>{if(confirm('Remove your character, discoveries, seeds, and sanctuary plantings from this browser?'))actions.onReset()})}
 return{clear,showStart,showImport,showAI,showCharacter,showJournal,showHelp};
}
