import { describe,expect,it } from 'vitest';
import { generateCharacter } from '../domain/character'; import { createInitialState } from '../domain/simulation'; import { createSaveStore } from './save-store';
class MemoryStorage{data=new Map<string,string>();getItem(k:string){return this.data.get(k)??null}setItem(k:string,v:string){this.data.set(k,v)}removeItem(k:string){this.data.delete(k)}}
describe('save store',()=>{
 it('round trips game state',()=>{const storage=new MemoryStorage(),store=createSaveStore(storage);expect(store.load().kind).toBe('empty');const state=createInitialState(generateCharacter(4));store.save(state);const result=store.load();expect(result.kind).toBe('loaded');if(result.kind==='loaded')expect(result.state.character).toEqual(state.character)});
 it('clears high-resolution transient effect deadlines when a save is loaded',()=>{const storage=new MemoryStorage(),store=createSaveStore(storage);const state=createInitialState(generateCharacter(4));state.effects={rootedUntil:980000,fragileUntil:980000,fadingUntil:980000,awakeProps:['sign']};store.save(state);const result=store.load();expect(result.kind).toBe('loaded');if(result.kind==='loaded')expect(result.state.effects).toEqual({rootedUntil:0,fragileUntil:0,fadingUntil:0,awakeProps:['sign']})});
 it('preserves malformed data as a diagnostic',()=>{const storage=new MemoryStorage();storage.setItem('unwritten.prototype.save.v1','not-json');const store=createSaveStore(storage);expect(store.load().kind).toBe('corrupt');expect(store.exportDiagnostic()).toBe('not-json')});
 it('refuses and preserves newer saves until the player explicitly clears them',()=>{const storage=new MemoryStorage(),raw=JSON.stringify({version:2,memories:['future']});storage.setItem('unwritten.prototype.save.v1',raw);const store=createSaveStore(storage);expect(store.load().kind).toBe('newer-version');expect(store.exportDiagnostic()).toBe(raw);expect(storage.getItem('unwritten.prototype.save.v1')).toBe(raw);store.clear();expect(store.load().kind).toBe('empty')});
});
