import { activateGift, activateShrine, inspectNearest, movePlayer, nearestTarget, plantSeed, removePlanting } from './domain/simulation'; import type { GameState, InteractionResult } from './domain/types'; import { SEED_NAMES } from './domain/world'; import type { createSaveStore } from './persistence/save-store'; import type { createCanvasRenderer } from './ui/canvas-renderer'; import type { createPanels } from './ui/panels';
type Renderer=ReturnType<typeof createCanvasRenderer>; type Panels=ReturnType<typeof createPanels>; type Store=ReturnType<typeof createSaveStore>;
export function createGameController(initial:GameState,renderer:Renderer,panels:Panels,store:Store,hud:HTMLElement,toastRoot:HTMLElement){let state=initial;const keys=new Set<string>();let previous=performance.now(),toastTimer=0;
 function toast(message:string){toastRoot.replaceChildren();const d=document.createElement('div');d.className='toast';d.textContent=message;toastRoot.append(d);clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>d.remove(),3200)}
 function updateHud(){hud.innerHTML=`<div class="hud-top"><div class="hud-card identity"><div class="identity-mark">?</div><div><strong data-testid="player-name"></strong><small></small></div></div><div class="hud-actions"><button data-testid="character-button" aria-label="Character passport">C</button><button data-testid="journal-button" aria-label="Field journal">J</button><button data-testid="help-button" aria-label="Help">?</button></div></div><div class="prompt"><span class="key">F</span> Gift · <span class="key">E</span> Inspect / resonate · <span class="hud-meta"></span></div>`;(hud.querySelector('[data-testid=player-name]') as HTMLElement).textContent=state.character.name;(hud.querySelector('.identity small') as HTMLElement).textContent=`${state.character.gift.name} · ${state.character.burden.name}`;(hud.querySelector('.hud-meta') as HTMLElement).textContent=state.borrowedGift?`Borrowing ${state.borrowedGift}`:`${state.seeds.length} seeds`;hud.querySelector('[data-testid=character-button]')?.addEventListener('click',()=>panels.showCharacter(state.character));hud.querySelector('[data-testid=journal-button]')?.addEventListener('click',()=>panels.showJournal(state));hud.querySelector('[data-testid=help-button]')?.addEventListener('click',panels.showHelp)}
 function apply(r:InteractionResult){state=r.state;if(r.changed){store.save(state);updateHud()}toast(r.message)}
 function interact(){const t=nearestTarget(state);if(!t||t.distance>160){apply(inspectNearest(state));return}if(t.type==='shrine'){apply(activateShrine(state));return}if(t.type==='plot'){const planted=state.plantings[t.value.id];if(planted){if(confirm(`Return ${SEED_NAMES[planted]??planted} to the seed tray?`))apply(removePlanting(state,t.value.id));return}const seed=state.seeds[0];if(seed){apply(plantSeed(state,t.value.id,seed));return}}apply(inspectNearest(state))}
 function keydown(e:KeyboardEvent){if((e.target as HTMLElement).matches('textarea,input'))return;keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==='f')apply(activateGift(state,performance.now()));if(e.key.toLowerCase()==='e')interact();if(e.key.toLowerCase()==='j')panels.showJournal(state);if(e.key.toLowerCase()==='c')panels.showCharacter(state.character)}
 function frame(now:number){const dt=Math.min(40,now-previous);previous=now;let dx=0,dy=0;if(keys.has('w')||keys.has('arrowup'))dy--;if(keys.has('s')||keys.has('arrowdown'))dy++;if(keys.has('a')||keys.has('arrowleft'))dx--;if(keys.has('d')||keys.has('arrowright'))dx++;if(dx||dy){const l=Math.hypot(dx,dy);state=movePlayer(state,{x:dx/l*dt*.24,y:dy/l*dt*.24},now);if(Math.floor(now/500)!==Math.floor((now-dt)/500))store.save(state)}renderer.render(state,now);requestAnimationFrame(frame)}
 addEventListener('keydown',keydown);addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('resize',renderer.resize);panels.clear();updateHud();store.save(state);requestAnimationFrame(frame);toast(`Welcome, ${state.character.name}. Your Gift is ${state.character.gift.name}.`);return{getState:()=>state,destroy:()=>{removeEventListener('keydown',keydown)}}}
